
  [en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1

  [zh]
    contentDir = "content/zh"
    languageName = "中文"
    weight = 2

  [ru]
    contentDir = "content/ru"
    languageName = "Russian"
    weight = 3