[[docs]]
  name = "О Hugo"
  weight = 10
  identifier = "about"
  url = "/about/"

[[docs]]
  name = "Установка Hugo"
  weight = 20
  identifier = "installation"
  url = "/installation/"

[[docs]]
  name = "С чего начать"
  weight = 30
  identifier = "getting-started"
  url = "/getting-started/"

[[docs]]
  name = "Модули Hugo"
  weight = 40
  identifier = "modules"
  post = "break"
  url = "/hugo-modules/"

# Core menus

[[docs]]
  name = "Управление контентом"
  weight = 50
  identifier = "content-management"
  post = "expanded"
  url = "/content-management/"

[[docs]]
  name = "Шаблоны"
  weight = 60
  identifier = "templates"
  url = "/templates/"

[[docs]]
  name = "Функции"
  weight = 70
  identifier = "functions"
  url = "/functions/"

[[docs]]
  name = "Переменные"
  weight = 80
  identifier = "variables"
  url = "/variables/"

[[docs]]
  name = "Обработчики Hugo Pipes"
  weight = 90
  identifier = "pipes"
  url = "/hugo-pipes/"

[[docs]]
  name = "Интерфейс командной строки CLI"
  weight = 100
  post = "break"
  identifier = "commands"
  url = "/commands/"

# Low level items

[[docs]]
  name = "Исправление проблем"
  weight = 110
  identifier = "troubleshooting"
  url = "/troubleshooting/"

[[docs]]
  name = "Инструменты"
  weight = 120
  identifier = "tools"
  url = "/tools/"

[[docs]]
  name = "Публикация на хостинге"
  weight = 130
  identifier = "hosting-and-deployment"
  url = "/hosting-and-deployment/"

[[docs]]
  name = "Сделать вклад"
  weight = 140
  post = "break"
  identifier = "contribute"
  url = "/contribute/"

######## QUICKLINKS

[[quicklinks]]
  name = "Основы"
  weight = 1
  identifier = "fundamentals"
  url = "/tags/fundamentals/"

######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "Новости"
    weight = 1
    identifier = "news"
    url = "/news/"

[[global]]
  name = "Документация"
  weight = 5
  identifier = "docs"
  url = "/documentation/"

[[global]]
  name = "Темы"
  weight = 10
  identifier = "themes"
  url = "https://themes.gohugo.io/"

[[global]]
  name = "Витрина"
  weight = 20
  identifier = "showcase"
  url = "/showcase/"

# Anything with a weight > 100 gets an external icon

[[global]]
  name = "Сообщество"
  weight = 150
  icon = true
  identifier = "community"
  post = "external"
  url = "https://discourse.gohugo.io/"

[[global]]
  name = "GitHub"
  weight = 200
  identifier = "github"
  post = "external"
  url = "https://github.com/gohugoio/hugo"
